### ISSUE TITLE
In eval_result TypeError: boolean value of NA is ambiguous and in data.append_test_result_to_sheets InvalidJsonError

### ISSUE THREAD

**Issue by krishnapadm** [GoogleCloudPlatform/dfcx-scrapi#234] opened 2024-09-13 15:10 UTC
## Expected Behavior
 currently these values are processed [None, "", "NaN", "nan"] but not NA

## Current Behavior
![image (18)](https://github.com/user-attachments/assets/205ccc30-b524-4141-aa15-25ba976a389a)

![image (19)](https://github.com/user-attachments/assets/24b6c614-5c57-4676-ad34-0925c2feea61)

**Comment by kmaphoenix** [comment] 2024-10-07 07:57
@krishnapadm this is a duplicate of #230 
The fix is being applied in #250

**Closed by kmaphoenix** 2024-10-07 07:57 UTC
Labels: bug, Evaluations
