### ISSUE TITLE
[BUG] Metrics for Evals should be Optional; Currently Tool Quality is hard set

### ISSUE THREAD

**Issue by agutta** [GoogleCloudPlatform/dfcx-scrapi#242] opened 2024-10-01 20:45 UTC
Calling [vertex eval set](https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/main/examples/vertex_ai_conversation/vertex_agents_evals.ipynb) is forcing to add a tool call.

## Expected Behavior
If the playbook we are testing dont have a Tool call it should not be mandatory to add a tool call in the input sheet.

## Current Behavior
Need to add a Tool call in the input sheet otherwise this line throws an error.
data.append_test_results_to_sheets(eval_results, sheet_name, summary_tab="reporting")

```
ValueError: Out of range float values are not JSON compliant

During handling of the above exception, another exception occurred:

InvalidJSONError                          Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/requests/models.py](https://localhost:8080/#) in prepare_body(self, data, files, json)
    510                 body = complexjson.dumps(json, allow_nan=False)
    511             except ValueError as ve:
--> 512                 raise InvalidJSONError(ve, request=self)
    513 
    514             if not isinstance(body, bytes):

InvalidJSONError: Out of range float values are not JSON compliant
```

===============================================================

Trying to removing the tool_call_quality does not help getting a different error
evals = Evaluations(agent_id, metrics=["response_similarity", "tool_call_quality"])

```
KeyError: 'tool_name_match'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
4 frames
/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py in get_loc(self, key)
   3810             ):
   3811                 raise InvalidIndexError(key)
-> 3812             raise KeyError(key) from err
   3813         except TypeError:
   3814             # If we have a listlike key, _check_indexing_error will raise

KeyError: 'tool_name_match'
```

**Comment by kmaphoenix** [comment] 2024-10-07 07:54
Closing as duplicate of #230 
Fix is being applied in #250

**Closed by kmaphoenix** 2024-10-07 07:54 UTC
Labels: bug
